package com.dbaagent.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Entity for storing index recommendations
 * Generated by analyzing query patterns and performance data
 */
@Entity
@Table(name = "index_recommendations", indexes = {
    @Index(name = "idx_rec_connection_id", columnList = "connectionId"),
    @Index(name = "idx_rec_status", columnList = "status"),
    @Index(name = "idx_rec_priority", columnList = "priority")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class IndexRecommendationEntity {

    public enum Priority {
        HIGH,      // Critical performance impact
        MEDIUM,    // Moderate performance impact
        LOW        // Minor performance impact
    }

    public enum Status {
        PENDING,   // Not yet applied
        APPLIED,   // User marked as applied
        DISMISSED  // User dismissed recommendation
    }

    public enum Kind {
        CREATE_INDEX,  // Suggest a new index to satisfy a missing-index pattern
        DROP_INDEX     // Suggest dropping an existing index that's never used
    }

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    @Column(nullable = false)
    private String connectionId;

    @Column(nullable = false)
    private String tableName;

    @Column(nullable = false)
    private String columnNames;  // Comma-separated column names

    @Column(nullable = false)
    private String indexName;  // Suggested index name

    @Column(nullable = false, columnDefinition = "TEXT")
    private String createStatement;  // CREATE INDEX statement

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private Priority priority;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private Status status = Status.PENDING;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    @Builder.Default
    private Kind kind = Kind.CREATE_INDEX;

    @Column
    private Integer estimatedImpact;  // Estimated performance improvement (0-100)

    @Column(columnDefinition = "TEXT")
    private String reason;  // Why this index is recommended

    @Column
    private Integer affectedQueries;  // Number of queries that would benefit

    @Column
    private Double avgPerformanceGain;  // Average expected score improvement

    /**
     * Total query time (ms) attributable to this candidate over the lookback
     * window: {@code Σ (calls × mean_exec_time_ms)} across slow queries that
     * touched the candidate columns in the matching role.
     *
     * This is the DBA-grade ROI metric — pganalyze "total time", Microsoft DTA
     * "expected workload cost reduction". Top-N ranking orders by net benefit
     * ({@code workload_score_ms - write_cost_score}) descending.
     */
    @Column(name = "workload_score_ms", nullable = false)
    @Builder.Default
    private Long workloadScoreMs = 0L;

    /**
     * Approximate per-write cost from {@code pg_stat_user_tables.n_tup_ins +
     * n_tup_upd + n_tup_del}. Subtracted from {@code workloadScoreMs} when
     * ranking so a new index on a write-heavy table needs to clear a much
     * higher read-savings bar.
     */
    @Column(name = "write_cost_score", nullable = false)
    @Builder.Default
    private Long writeCostScore = 0L;

    /**
     * How many distinct contributing queries are persisted in
     * {@code index_recommendation_evidence} for this recommendation.
     * Separate from {@code occurrenceCount} (which counts cycle re-observations).
     */
    @Column(name = "evidence_count", nullable = false)
    @Builder.Default
    private Integer evidenceCount = 0;

    /**
     * Planner-reported cost of the contributing queries BEFORE the hypothetical
     * index existed. Populated by {@code PostgresHypotheticalCostEstimator}
     * when HypoPG is installed on the target connection; null otherwise.
     */
    @Column(name = "hypopg_before_cost")
    private Double hypopgBeforeCost;

    /**
     * Same plan cost AFTER the hypothetical index was created via
     * {@code hypopg_create_index()}. The difference proves the planner will
     * actually use the recommended index — distinguishes "would-be" wins
     * from "the heuristic says yes but the planner wouldn't switch."
     */
    @Column(name = "hypopg_after_cost")
    private Double hypopgAfterCost;

    /**
     * {@code (before − after) / before × 100}. Null means HypoPG didn't run
     * (extension missing, MySQL, query had parameter placeholders we couldn't
     * substitute, etc.).
     */
    @Column(name = "hypopg_reduction_pct")
    private Double hypopgReductionPct;

    @Column(name = "hypopg_evaluated_at")
    private LocalDateTime hypopgEvaluatedAt;

    /**
     * How many refresh cycles have re-observed this (table, columns) candidate.
     * Drives top-N ranking — recommendations grounded in many days of slow-log
     * evidence outrank one-shot finds.
     */
    @Column(nullable = false)
    @Builder.Default
    private Integer occurrenceCount = 1;

    @Column
    private LocalDateTime firstSeenAt;

    @Column
    private LocalDateTime lastSeenAt;

    @Column(nullable = false)
    private LocalDateTime createdAt;

    @Column
    private LocalDateTime updatedAt;

    @Column
    private LocalDateTime appliedAt;

    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        if (createdAt == null) {
            createdAt = now;
        }
        if (firstSeenAt == null) {
            firstSeenAt = now;
        }
        if (lastSeenAt == null) {
            lastSeenAt = now;
        }
        if (occurrenceCount == null) {
            occurrenceCount = 1;
        }
        if (workloadScoreMs == null) workloadScoreMs = 0L;
        if (writeCostScore == null) writeCostScore = 0L;
        if (evidenceCount == null) evidenceCount = 0;
        updatedAt = now;
    }

    /**
     * Workload time saved minus write-amplification cost. Drives the top-N
     * ranking. Always non-negative for display (negative means the index is
     * a net cost; ranked below higher-net-benefit candidates anyway).
     */
    public long netBenefitMs() {
        long w = workloadScoreMs == null ? 0L : workloadScoreMs;
        long c = writeCostScore  == null ? 0L : writeCostScore;
        return Math.max(0L, w - c);
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    /**
     * Mark this recommendation as applied
     */
    public void markAsApplied() {
        this.status = Status.APPLIED;
        this.appliedAt = LocalDateTime.now();
    }

    /**
     * Record that this (table, columns) candidate was re-observed in a fresh
     * refresh cycle. Bumps the recurrence counter and updates last-seen so
     * recurring slow-query patterns surface ahead of one-shot finds.
     */
    public void recordRecurrence() {
        this.occurrenceCount = (this.occurrenceCount == null ? 0 : this.occurrenceCount) + 1;
        this.lastSeenAt = LocalDateTime.now();
    }

    /**
     * Mark this recommendation as dismissed
     */
    public void dismiss() {
        this.status = Status.DISMISSED;
    }
}
