"use client";

import { XCircle } from "lucide-react";
import { useState } from "react";
import styles from "../../Core/RagTrainingTab.module.css";

/**
 * Modal for adding/editing table and column documentation
 */
export function NoteModal({
  isOpen,
  noteData,
  noteForm,
  onUpdateForm,
  onSubmit,
  onClose,
  tableOptions = [],
  columnOptions = [],
  saving = false,
  actionStatus = null,
}) {
  const [showAmbiguousDocTables, setShowAmbiguousDocTables] = useState(false);

  if (!isOpen) return null;

  const handleSubmit = (e) => {
    e.preventDefault();
    onSubmit();
  };

  return (
    <div className={styles.modalOverlay} onClick={onClose}>
      <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
        <div className={styles.modalHeader}>
          <div>
            <div className={styles.modalTitle}>
              {noteData?.noteId ? "Edit details" : "Add details"}
            </div>
            <div className={styles.modalSubtitle}>
              {noteForm.scopeType === "COLUMN"
                ? `${noteForm.tableName}.${noteForm.columnName}`
                : noteForm.tableName || "Database detail"}
            </div>
          </div>
          <button
            className={styles.modalCloseButton}
            onClick={onClose}
            aria-label="Close"
          >
            <XCircle size={18} />
          </button>
        </div>

        <form className={styles.modalBody} onSubmit={handleSubmit}>
          {noteData?.source === "AI_GENERATED" && (
            <div
              style={{
                padding: "8px 12px",
                background: "#f0f0ff",
                borderRadius: "6px",
                fontSize: "12px",
                color: "#6366f1",
                marginBottom: "12px",
              }}
            >
              This description was generated by AI. Your edits will override the
              AI version.
            </div>
          )}

          {noteData?.reason && (
            <div className={styles.docHint}>
              <strong>Why we need this:</strong> {noteData.reason}
            </div>
          )}

          {noteData?.ambiguousTables?.length ? (
            <div className={styles.docHint}>
              <div className={styles.docHintRow}>
                <strong>Ambiguous tables:</strong>{" "}
                {noteData.ambiguousTables.length}
                {noteData.ambiguousTables.length > 12 ? (
                  <button
                    type="button"
                    className={styles.hintToggle}
                    onClick={() => setShowAmbiguousDocTables((prev) => !prev)}
                  >
                    {showAmbiguousDocTables ? "Hide list" : "Show list"}
                  </button>
                ) : null}
              </div>
              {showAmbiguousDocTables ||
              noteData.ambiguousTables.length <= 12 ? (
                <div className={styles.ambiguousList}>
                  {noteData.ambiguousTables.join(", ")}
                </div>
              ) : null}
            </div>
          ) : null}

          <div className={styles.formField}>
            <label>Scope</label>
            <select
              value={noteForm.scopeType}
              onChange={(e) =>
                onUpdateForm({
                  scopeType: e.target.value,
                  columnName:
                    e.target.value === "TABLE" ? "" : noteForm.columnName,
                })
              }
              disabled={noteData?.locked}
            >
              <option value="TABLE">Table</option>
              <option value="COLUMN">Column</option>
            </select>
          </div>

          <div className={styles.formField}>
            <label>Table</label>
            <input
              list="brain-table-options"
              value={noteForm.tableName}
              onChange={(e) => onUpdateForm({ tableName: e.target.value })}
              placeholder="Table name"
              readOnly={noteData?.locked}
              required
            />
            <datalist id="brain-table-options">
              {tableOptions.map((tableName) => (
                <option key={tableName} value={tableName} />
              ))}
            </datalist>
          </div>

          {noteForm.scopeType === "COLUMN" ? (
            <div className={styles.formField}>
              <label>Column</label>
              <input
                list="brain-column-options"
                value={noteForm.columnName}
                onChange={(e) => onUpdateForm({ columnName: e.target.value })}
                placeholder="Column name"
                readOnly={noteData?.locked}
                required
              />
              <datalist id="brain-column-options">
                {columnOptions.map((columnName) => (
                  <option key={columnName} value={columnName} />
                ))}
              </datalist>
            </div>
          ) : null}

          <div className={styles.formField}>
            <label>Details</label>
            <textarea
              value={noteForm.noteText}
              onChange={(e) => onUpdateForm({ noteText: e.target.value })}
              placeholder="Explain what this table or column represents"
              required
            />
          </div>

          <div className={styles.noteHint}>
            This text is embedded into Brain and RAG retrieval results.
          </div>

          {actionStatus ? (
            <div className={styles.noteStatus}>{actionStatus}</div>
          ) : null}

          <div className={styles.modalActions}>
            <button
              type="button"
              className={styles.cancelButton}
              onClick={onClose}
            >
              Cancel
            </button>
            <button
              type="submit"
              className={styles.trainButton}
              disabled={saving}
            >
              {saving ? "Saving..." : "Save details"}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
