"use client";

import { useState, useEffect, useMemo, useCallback } from "react";
import { format as sqlFormat } from "sql-formatter";
import {
  X,
  Sparkles,
  Circle,
  AlertTriangle,
  Copy,
  Check,
  Database,
  ChevronDown,
  ChevronRight,
  Info,
  RefreshCw,
  Clock,
  BarChart2,
  Zap,
  List,
  TrendingUp,
  TrendingDown,
  Minus,
} from "lucide-react";
import { HelpTooltip } from "@/components/tabs/Brain/components/HelpTooltip";
import styles from "./QueryDetailDialog.module.css";

const QUERY_ID_HELP = {
  title: "Query ID",
  description: "A stable fingerprint of the query pattern after normalization.",
  impact:
    "Used to group executions, track regressions, and cache AI optimizations across refreshes.",
  optimization:
    "Generated by removing literals (values) from SQL, normalizing whitespace, then hashing the result.",
};

function renderMarkdown(text) {
  if (!text) return null;
  const lines = text.split("\n");
  const elements = [];
  let i = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (line.trim().startsWith("|")) {
      const tableLines = [];
      while (i < lines.length && lines[i].trim().startsWith("|")) {
        tableLines.push(lines[i].trim());
        i++;
      }
      if (tableLines.length >= 2) {
        const parseRow = (row) =>
          row.split("|").map((c) => c.trim()).filter(Boolean);
        const header = parseRow(tableLines[0]);
        const startIdx = tableLines[1].includes("---") ? 2 : 1;
        const bodyRows = tableLines.slice(startIdx).map(parseRow);
        elements.push(
          <div key={`tbl-${elements.length}`} className={styles.mdTable}>
            <table>
              <thead><tr>{header.map((h, hi) => <th key={hi}>{h}</th>)}</tr></thead>
              <tbody>{bodyRows.map((row, ri) => <tr key={ri}>{row.map((cell, ci) => <td key={ci}>{cell}</td>)}</tr>)}</tbody>
            </table>
          </div>
        );
      }
      continue;
    }

    if (/^\s*[-*]\s/.test(line)) {
      const listItems = [];
      while (i < lines.length && /^\s*[-*]\s/.test(lines[i])) {
        listItems.push(lines[i].replace(/^\s*[-*]\s+/, ""));
        i++;
      }
      elements.push(
        <ul key={`ul-${elements.length}`} className={styles.mdList}>
          {listItems.map((item, li) => <li key={li}>{renderInline(item)}</li>)}
        </ul>
      );
      continue;
    }

    if (line.trim()) {
      elements.push(<p key={`p-${elements.length}`} className={styles.mdPara}>{renderInline(line)}</p>);
    }
    i++;
  }
  return <>{elements}</>;
}

function renderInline(text) {
  const parts = [];
  let remaining = text;
  let key = 0;
  while (remaining.length > 0) {
    const boldMatch = remaining.match(/\*\*(.+?)\*\*/);
    const italicMatch = remaining.match(/(?<!\*)\*(?!\*)(.+?)(?<!\*)\*(?!\*)/);
    const codeMatch = remaining.match(/`([^`]+)`/);
    const firstMatch = [boldMatch, italicMatch, codeMatch].filter(Boolean).sort((a, b) => a.index - b.index)[0];
    if (!firstMatch) { parts.push(remaining); break; }
    if (firstMatch.index > 0) parts.push(remaining.substring(0, firstMatch.index));
    if (firstMatch === boldMatch) parts.push(<strong key={key++}>{firstMatch[1]}</strong>);
    else if (firstMatch === italicMatch) parts.push(<em key={key++}>{firstMatch[1]}</em>);
    else parts.push(<code key={key++} className={styles.mdInlineCode}>{firstMatch[1]}</code>);
    remaining = remaining.substring(firstMatch.index + firstMatch[0].length);
  }
  return parts;
}

const STEP_STATUS_CONFIG = {
  analyzing:           { icon: "🔍", label: "Analyzing",      color: "#6B7280" },
  checking:            { icon: "🤔", label: "Assessing",      color: "#6B7280" },
  no_rewrite:          { icon: "ℹ️",  label: "No rewrite",    color: "#6B7280" },
  rewrite_generated:   { icon: "✏️",  label: "Generated",     color: "#6B7280" },
  validating_rows:     { icon: "🔢", label: "Validating",     color: "#6B7280" },
  rows_validated:      { icon: "✅", label: "Rows match",     color: "#16a34a" },
  rewrite_incorrect:   { icon: "❌", label: "Incorrect",      color: "#dc2626" },
  benchmarking:        { icon: "⏱️",  label: "Benchmarking",  color: "#6B7280" },
  rewrite_accepted:    { icon: "✅", label: "Accepted",       color: "#16a34a" },
  rewrite_rejected:    { icon: "🚫", label: "Discarded",      color: "#dc2626" },
  benchmark_skipped:   { icon: "⚠️",  label: "Unvalidated",   color: "#d97706" },
};

/** Highlight string literals and numeric literals inside a SQL string */
function HighlightedQuery({ sql }) {
  if (!sql) return null;
  const tokens = [];
  const regex = /'(?:[^'\\]|\\.)*'|"(?:[^"\\]|\\.)*"|\b(\d{4}-\d{2}-\d{2}(?:[ T]\d{2}:\d{2}:\d{2})?)\b|\b(\d+(?:\.\d+)?)\b/g;
  let lastIndex = 0;
  let match;
  while ((match = regex.exec(sql)) !== null) {
    if (match.index > lastIndex) tokens.push({ type: "plain", text: sql.slice(lastIndex, match.index) });
    const t = match[0];
    const isString = t.startsWith("'") || t.startsWith('"');
    const isDate = match[1] != null;
    tokens.push({ type: isDate ? "lit-date" : isString ? "lit-string" : "lit-number", text: t });
    lastIndex = regex.lastIndex;
  }
  if (lastIndex < sql.length) tokens.push({ type: "plain", text: sql.slice(lastIndex) });
  return (
    <>
      {tokens.map((tok, i) => {
        if (tok.type === "lit-string") return <mark key={i} className={styles.litString}>{tok.text}</mark>;
        if (tok.type === "lit-date")   return <mark key={i} className={styles.litDate}>{tok.text}</mark>;
        if (tok.type === "lit-number") return <mark key={i} className={styles.litNumber}>{tok.text}</mark>;
        return <span key={i}>{tok.text}</span>;
      })}
    </>
  );
}

function OptimizationStepList({ steps }) {
  if (!steps || steps.length === 0) return null;
  return (
    <div className={styles.stepList}>
      {steps.map((step, i) => {
        const cfg = STEP_STATUS_CONFIG[step.status] || { icon: "•", color: "#6B7280" };
        const isLast = i === steps.length - 1;
        return (
          <div key={i} className={styles.stepItem} style={{ opacity: isLast ? 1 : 0.6 }}>
            <span className={styles.stepIcon}>{cfg.icon}</span>
            <div className={styles.stepBody}>
              <span className={styles.stepMessage} style={{ color: cfg.color }}>{step.message}</span>
              {step.detail && <div className={styles.stepDetail}>{step.detail}</div>}
            </div>
          </div>
        );
      })}
    </div>
  );
}

export default function QueryDetailDialog({
  query,
  open,
  onOpenChange,
  onOptimize,
  onBenchmarkCandidates,
  optimization,
  optimizationCandidates,
  isBenchmarkingCandidates = false,
  isOptimizing = false,
  optimizationSteps = [],
  fingerprintData = null,
}) {
  const [activeTab, setActiveTab] = useState("overview");
  const [copiedId, setCopiedId] = useState(null);
  const [expandedSections, setExpandedSections] = useState({ planTree: false, tableAccess: true, issues: true });

  const handleCopy = async (text, id = "default") => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedId(id);
      setTimeout(() => setCopiedId(null), 2000);
    } catch { /* silent */ }
  };

  const handleClose = () => { onOpenChange(false); };
  const toggleSection = (s) => setExpandedSections((p) => ({ ...p, [s]: !p[s] }));

  const stripSlowLogPrefix = (sql) => {
    if (!sql) return sql;
    return sql.replace(/^\s*use\s+\S+;\s*/i, "").replace(/^\s*SET\s+timestamp=\d+;\s*/i, "").trim();
  };

  const formatDuration = (ms) => {
    if (!ms && ms !== 0) return "N/A";
    if (ms >= 1000) return `${(ms / 1000).toFixed(2)}s`;
    return `${ms.toFixed(0)}ms`;
  };

  const formatNumber = (num) => {
    if (!num && num !== 0) return "0";
    if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
    if (num >= 1000) return `${(num / 1000).toFixed(1)}K`;
    return num.toString();
  };

  const formatCost = (cost) => {
    if (!cost && cost !== 0) return "—";
    if (cost >= 1000000) return `${(cost / 1000000).toFixed(1)}M`;
    if (cost >= 1000) return `${(cost / 1000).toFixed(1)}K`;
    return cost.toFixed(2);
  };

  const formatDate = (ts) => {
    if (!ts) return "—";
    try {
      return new Date(ts).toLocaleDateString(undefined, { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
    } catch { return "—"; }
  };

  // ── Derived data ──────────────────────────────────────────────────────────

  const candidates = optimizationCandidates?.candidates || [];
  const bestCandidate = optimizationCandidates?.bestOverall || null;
  const rewriteCandidate = candidates.find((c) => c.candidateId === "AI_REWRITE");
  const baselineCandidate = candidates.find((c) => c.candidateId === "ORIGINAL");
  const rewriteBenchmark = rewriteCandidate?.medianMs ?? rewriteCandidate?.benchmarkMs ?? null;

  // Determine rewritten SQL early so it can gate downstream computations
  const optimizedQuery = optimization?.optimizedQuery || "";
  const rewrittenSql = rewriteCandidate?.candidateSql || optimizedQuery || null;

  const queryAvgMs =
    query?.avgDurationMs ?? query?.avgExecutionTimeMs ?? query?.averageDurationMs ?? null;
  const baselineRuntime = queryAvgMs;

  // Only compute estimated improvement when a rewritten query was actually accepted
  const parsedImprovement = rewrittenSql ? (() => {
    const raw = optimization?.estimatedImprovement;
    if (raw != null) {
      if (typeof raw === "number") return raw;
      const str = String(raw);
      const rangeMatch = str.match(/(\d+)\s*[-–]\s*(\d+)/);
      if (rangeMatch) return (parseFloat(rangeMatch[1]) + parseFloat(rangeMatch[2])) / 2;
      const singleMatch = str.match(/(\d+(?:\.\d+)?)/);
      if (singleMatch) return parseFloat(singleMatch[1]);
    }
    const suggestions = optimization?.suggestions || [];
    const impacts = suggestions.map((s) => s?.estimatedImpact).filter((v) => typeof v === "number" && v > 0 && v <= 100);
    if (impacts.length > 0) return Math.max(...impacts);
    const explanation = optimization?.explanation || "";
    if (explanation) {
      const rangeMatch = explanation.match(/(\d{1,3})\s*[-–]\s*(\d{1,3})\s*%/i);
      if (rangeMatch) { const mid = (parseFloat(rangeMatch[1]) + parseFloat(rangeMatch[2])) / 2; if (mid >= 1 && mid <= 99) return mid; }
      const pctMatch = explanation.match(/(\d{1,3}(?:\.\d+)?)\s*%\s*(?:improvement|faster|better|reduction|speedup)/i);
      if (pctMatch) { const val = parseFloat(pctMatch[1]); if (val >= 1 && val <= 99) return val; }
      const multMatch = explanation.match(/(\d+(?:\.\d+)?)\s*[xX]\s+(?:faster|improvement|speedup|better)/i);
      if (multMatch) { const mult = parseFloat(multMatch[1]); if (mult > 1 && mult <= 100) return Math.round((1 - 1 / mult) * 1000) / 10; }
    }
    return null;
  })() : null;

  const estimatedNewRuntime = parsedImprovement != null && queryAvgMs != null ? queryAvgMs * (1 - parsedImprovement / 100) : null;
  const rewriteRuntime = rewrittenSql ? (rewriteBenchmark ?? estimatedNewRuntime) : null;
  const rewriteIsMeasured = rewriteBenchmark != null;
  const originalRowCount = baselineCandidate?.rowCountResult ?? null;
  const rewriteRowCount = rewriteCandidate?.rowCountResult ?? null;
  const rowCountMismatch = originalRowCount != null && rewriteRowCount != null && originalRowCount !== rewriteRowCount;
  const zeroRowBenchmark = originalRowCount != null && originalRowCount === 0;
  const compareDeltaPct = baselineRuntime != null && rewriteRuntime != null && baselineRuntime > 0
    ? ((baselineRuntime - rewriteRuntime) / baselineRuntime) * 100 : null;

  const actualQuery = stripSlowLogPrefix(query?.sampleQuery || null);
  const rawDisplayQuery = actualQuery || stripSlowLogPrefix(query?.queryText || query?.query) || "N/A";
  const displayQuery = useMemo(() => {
    if (!rawDisplayQuery || rawDisplayQuery === "N/A") return rawDisplayQuery;
    try {
      return sqlFormat(rawDisplayQuery, { language: "mysql", tabWidth: 2, keywordCase: "upper" });
    } catch {
      return rawDisplayQuery;
    }
  }, [rawDisplayQuery]);
  const normalizedQuery = stripSlowLogPrefix(query?.queryText || query?.query || null);
  const hasSampleLiterals = Boolean(actualQuery && normalizedQuery && actualQuery.trim().toLowerCase() !== normalizedQuery.trim().toLowerCase());
  const originalSql = baselineCandidate?.candidateSql || displayQuery;

  const [activeCompareTab, setActiveCompareTab] = useState("rewrite");
  const activeCompareSql = activeCompareTab === "original" ? originalSql : rewrittenSql;

  useEffect(() => {
    if (activeCompareTab === "rewrite" && !rewrittenSql && originalSql) setActiveCompareTab("original");
    else if (activeCompareTab === "original" && !originalSql && rewrittenSql) setActiveCompareTab("rewrite");
  }, [activeCompareTab, originalSql, rewrittenSql]);

  // Auto-switch to overview tab when optimization completes
  useEffect(() => {
    if (optimization && !isOptimizing) setActiveTab("overview");
  }, [optimization, isOptimizing]);

  // Reset tab when dialog opens fresh
  useEffect(() => {
    if (open) setActiveTab("overview");
  }, [open, query?.queryId]);

  // ── Suggestion parsing ────────────────────────────────────────────────────

  const rawSuggestions = optimization?.suggestions || [];
  const strategyItems = rawSuggestions.filter((s) => {
    if (!s?.title) return false;
    const t = s.title.trim(); const d = (s.description || "").trim();
    if (!t && !d) return false;
    if (/^\~?\d+[\–\-]?\d*\s*%$/.test(t) && !d) return false;
    if (/estimated\s+(impact|improvement|performance)/i.test(t)) return false;
    if (/overall\s+estimated/i.test(t)) return false;
    if (/^\d+%\s+(overall|performance|improvement|faster|better|reduction)/i.test(t)) return false;
    if (/^\d+[smhMKGT]?\s*[→>]\s*[<~]?\d+/.test(t)) return false;
    if (/^(key\s+)?assumptions?$/i.test(t)) return false;
    if (/^(context|background|note|summary|overview|conclusion)$/i.test(t)) return false;
    if (/^problems?$/i.test(t)) return false;
    if (t.length < 3 && d.length < 10) return false;
    const hasRealImpl = s.implementationSQL && !/^\s*--/.test(s.implementationSQL.trim());
    if (!d && !hasRealImpl) return false;
    return true;
  }).map((s) => {
    const cat = (s.category || "GENERAL").toUpperCase();
    const desc = (s.description || "").trim();
    const implSQL = (s.implementationSQL || "").trim();
    const bestText = desc.endsWith("...") && implSQL ? implSQL : desc;
    return { ...s, cat, bestText };
  });

  // ── EXPLAIN plan data ─────────────────────────────────────────────────────

  const explainAnalysis = optimization?.explainAnalysis || {};
  const planTree = explainAnalysis.planTree || null;
  const issues = explainAnalysis.issues || [];

  const parseExplainTreeText = (rawPlanText) => {
    let text = "";
    if (typeof rawPlanText === "string") {
      try {
        const parsed = JSON.parse(rawPlanText);
        if (Array.isArray(parsed) && parsed[0]?.raw) text = parsed[0].raw;
        else text = rawPlanText;
      } catch { text = rawPlanText; }
    }
    if (!text) return [];
    return text.split("\n").filter((l) => l.trim()).map((line) => {
      const indent = line.search(/\S/); const depth = Math.floor(indent / 4);
      const cleaned = line.trim().replace(/^->\s*/, "");
      const opMatch = cleaned.match(/^([^(]+?)(?:\s*\(|$)/);
      const operation = opMatch ? opMatch[1].trim() : cleaned;
      const costMatch = cleaned.match(/cost=([\d.e+]+)(?:\.\.([\d.e+]+))?/);
      const cost = costMatch ? parseFloat(costMatch[2] || costMatch[1]) : null;
      const estRowsMatch = cleaned.match(/cost=[\d.e+]+(?:\.\.[\d.e+]+)?\s+rows=([\d.e+]+)/);
      const estRows = estRowsMatch ? parseFloat(estRowsMatch[1]) : null;
      const timeMatch = cleaned.match(/actual time=([\d.e+]+)\.\.([\d.e+]+)/);
      const actualTimeStart = timeMatch ? parseFloat(timeMatch[1]) : null;
      const actualTimeEnd = timeMatch ? parseFloat(timeMatch[2]) : null;
      const actRowsMatch = cleaned.match(/actual time=[\d.e+]+\.\.[\d.e+]+\s+rows=([\d.e+]+)/);
      const actualRows = actRowsMatch ? parseFloat(actRowsMatch[1]) : null;
      const loopsMatch = cleaned.match(/loops=(\d+)/);
      const loops = loopsMatch ? parseInt(loopsMatch[1], 10) : null;
      return { operation, depth, cost, estRows, actualTimeStart, actualTimeEnd, actualRows, loops, raw: cleaned };
    });
  };

  const parsedTreeNodes = parseExplainTreeText(explainAnalysis.planText || explainAnalysis.planJson || "");
  const hasRealTreeData = parsedTreeNodes.length > 0;
  const maxTreeTime = parsedTreeNodes.reduce((max, n) => Math.max(max, n.actualTimeEnd || 0), 0);

  const treeHierarchy = useMemo(() => {
    if (!parsedTreeNodes.length) return [];
    const root = []; const stack = [];
    for (let i = 0; i < parsedTreeNodes.length; i++) {
      const node = { ...parsedTreeNodes[i], id: i, children: [] };
      while (stack.length > 0 && stack[stack.length - 1].depth >= node.depth) stack.pop();
      if (stack.length === 0) root.push(node);
      else stack[stack.length - 1].children.push(node);
      stack.push(node);
    }
    return root;
  }, [parsedTreeNodes]);

  const [explainViewMode, setExplainViewMode] = useState("tree");
  const [selectedVisualNodeId, setSelectedVisualNodeId] = useState(null);
  const [expandedTreeNodeIds, setExpandedTreeNodeIds] = useState(() => new Set([0]));
  const toggleTreeNode = useCallback((nodeId) => {
    setExpandedTreeNodeIds((prev) => { const next = new Set(prev); if (next.has(nodeId)) next.delete(nodeId); else next.add(nodeId); return next; });
  }, []);
  const expandAllTreeNodes = useCallback(() => setExpandedTreeNodeIds(new Set(parsedTreeNodes.map((_, i) => i))), [parsedTreeNodes]);
  const collapseAllTreeNodes = useCallback(() => setExpandedTreeNodeIds(new Set([0])), []);

  // ── Top executions ────────────────────────────────────────────────────────

  const topExecutions = useMemo(() => {
    const history = fingerprintData?.performanceHistory || [];
    if (history.length > 0) {
      return [...history].sort((a, b) => (b.avgTimeMs || 0) - (a.avgTimeMs || 0)).slice(0, 5);
    }
    // Synthesize from aggregate stats when no history is available
    const entries = [];
    if (query?.maxDurationMs || query?.maxExecutionTimeMs) {
      entries.push({
        label: "Worst execution",
        avgTimeMs: query.maxDurationMs || query.maxExecutionTimeMs,
        rowsExamined: query.rowsExamined,
        callCount: null,
        timestamp: query.lastSeen,
      });
    }
    if (query?.avgDurationMs || query?.avgExecutionTimeMs) {
      entries.push({
        label: "Average execution",
        avgTimeMs: query.avgDurationMs || query.avgExecutionTimeMs,
        rowsExamined: query.avgRowsExamined,
        callCount: query.callCount,
        timestamp: null,
      });
    }
    if (query?.minExecutionTimeMs) {
      entries.push({
        label: "Best execution",
        avgTimeMs: query.minExecutionTimeMs,
        rowsExamined: null,
        callCount: null,
        timestamp: null,
      });
    }
    return entries;
  }, [fingerprintData, query]);

  // ── Tabs definition ───────────────────────────────────────────────────────

  const showTabView = Boolean(optimization) && !isOptimizing;
  const tabs = useMemo(() => [
    { id: "overview",   label: "Overview",       icon: Info },
    { id: "executions", label: "Top Executions",  icon: Clock },
    { id: "rewrite",    label: "Query Rewrite",   icon: Sparkles },
    { id: "explain",    label: "Explain Plan",    icon: BarChart2, disabled: !hasRealTreeData && !planTree },
  ], [hasRealTreeData, planTree]);

  if (!open || !query) return null;

  // ── Tab renderers ─────────────────────────────────────────────────────────

  const renderOverviewTab = () => {
    // Structural issues from EXPLAIN — full table scans, missing indexes, etc.
    const explainIssues = explainAnalysis.issues || [];
    // Non-rewrite structural findings (INDEX, CONFIG, GENERAL — never QUERY_REWRITE)
    const structuralFindings = strategyItems.filter(
      (s) => s.cat !== "QUERY_REWRITE" && s.cat !== "REWRITE"
    );

    return (
      <div className={styles.tabContent}>
        {/* What does this query do — AI explanation */}
        {optimization?.explanation ? (
          <div className={styles.overviewSection}>
            <h4 className={styles.overviewSectionTitle}>
              <Info size={13} className={styles.overviewSectionIcon} />
              What This Query Does
            </h4>
            <div className={styles.overviewExplanation}>
              {renderMarkdown(optimization.explanation)}
            </div>
          </div>
        ) : (
          <div className={styles.overviewSection}>
            <h4 className={styles.overviewSectionTitle}>
              <Info size={13} className={styles.overviewSectionIcon} />
              What This Query Does
            </h4>
            <p className={styles.overviewPlaceholder}>
              Run analysis to get an AI-generated description of what this query does and why it's slow.
            </p>
          </div>
        )}

        {/* Performance Issues from EXPLAIN — full table scans, bad access patterns, etc. */}
        {explainIssues.length > 0 && (
          <div className={styles.overviewSection}>
            <h4 className={styles.overviewSectionTitle}>
              <AlertTriangle size={13} className={styles.overviewSectionIcon} />
              Performance Issues Detected
            </h4>
            <div className={styles.issuesList}>
              {explainIssues.map((issue, idx) => {
                const sev = (issue.severity || "medium").toLowerCase();
                const isCritical = sev === "critical" || sev === "high";
                return (
                  <div key={idx} className={`${styles.issueCard} ${isCritical ? styles.issueCardCritical : ""}`}>
                    <span className={`${styles.issueSeverity} ${styles[`sev${sev}`] || ""}`}>
                      {sev.toUpperCase()}
                    </span>
                    <span className={styles.issueDesc}>
                      {issue.description || issue.message || JSON.stringify(issue)}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Structural findings — index, config, schema (no rewrite) */}
        {structuralFindings.length > 0 && (
          <div className={styles.overviewSection}>
            <h4 className={styles.overviewSectionTitle}>
              <Zap size={13} className={styles.overviewSectionIcon} />
              Findings
            </h4>
            <div className={styles.findingsList}>
              {structuralFindings.slice(0, 5).map((s, i) => (
                <div key={i} className={styles.findingItem}>
                  <div className={styles.findingHeader}>
                    <span className={`${styles.findingCatBadge} ${styles[`findingCat${s.cat}`] || styles.findingCatGENERAL}`}>
                      {s.cat}
                    </span>
                    <span className={styles.findingTitle}>{s.title}</span>
                  </div>
                  {s.bestText && <p className={styles.findingDesc}>{s.bestText}</p>}
                  {s.implementationSQL && !/^\s*--/.test(s.implementationSQL.trim()) && s.bestText !== s.implementationSQL && (
                    <pre className={styles.findingCode}><code>{s.implementationSQL}</code></pre>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Index Recommendations */}
        {optimization?.indexRecommendations?.length > 0 && (
          <div className={styles.overviewSection}>
            <h4 className={styles.overviewSectionTitle}>
              <Database size={13} className={styles.overviewSectionIcon} />
              Index Recommendations
            </h4>
            <div className={styles.indexRecsBlock}>
              {optimization.indexRecommendations.map((rec, idx) => (
                <div key={idx} className={styles.indexRecItem}>
                  <Database size={11} className={styles.indexRecIcon} />
                  <code className={styles.indexRecCode}>{rec}</code>
                  <button className={styles.copySmall} onClick={() => handleCopy(rec, `idx-${idx}`)} title="Copy SQL">
                    {copiedId === `idx-${idx}` ? <Check size={10} /> : <Copy size={10} />}
                  </button>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    );
  };

  const renderExecutionsTab = () => {
    // Real execution snapshots from fingerprint performance history
    const history = fingerprintData?.performanceHistory || [];
    const sortedHistory = [...history]
      .sort((a, b) => (b.avgTimeMs || 0) - (a.avgTimeMs || 0))
      .slice(0, 5);
    const maxMs = sortedHistory[0]?.avgTimeMs || 1;
    // Representative sample query — prefer the one with actual literal values
    const sampleSql = fingerprintData?.sampleQuery || query?.sampleQuery || null;

    return (
      <div className={styles.tabContent}>
        {/* Representative query with highlighted literals */}
        {sampleSql && (
          <div className={styles.overviewSection}>
            <h4 className={styles.overviewSectionTitle}>
              <Clock size={13} className={styles.overviewSectionIcon} />
              Representative Query
              <span className={styles.overviewSectionHint}>literal values highlighted</span>
            </h4>
            <pre className={styles.queryCodeInner}>
              <code><HighlightedQuery sql={sampleSql} /></code>
            </pre>
          </div>
        )}

        {/* Execution snapshots table */}
        {sortedHistory.length > 0 ? (
          <div className={styles.overviewSection}>
            <h4 className={styles.overviewSectionTitle}>
              <TrendingUp size={13} className={styles.overviewSectionIcon} />
              Top Execution Snapshots
              <span className={styles.overviewSectionHint}>sorted by avg time · from slow log analysis</span>
            </h4>
            <div className={styles.executionsTable}>
              <div className={styles.executionsTableHeader}>
                <span className={styles.execCol}>Observed At</span>
                <span className={styles.execCol}>Avg Time</span>
                <span className={styles.execCol}>Calls</span>
                <span className={styles.execCol}>Rows Examined</span>
                <span className={styles.execCol}>Relative</span>
              </div>
              {sortedHistory.map((exec, i) => {
                const ms = exec.avgTimeMs || 0;
                const barPct = Math.max(4, (ms / maxMs) * 100);
                const isWorst = i === 0;
                return (
                  <div key={i} className={`${styles.executionsRow} ${isWorst ? styles.executionsRowWorst : ""}`}>
                    <span className={styles.execCol}>
                      {formatDate(exec.timestamp)}
                      {isWorst && <span className={styles.execBadgeWorst}>Slowest</span>}
                    </span>
                    <span className={`${styles.execCol} ${styles.execTime} ${isWorst ? styles.execTimeWorst : ""}`}>
                      {formatDuration(ms)}
                    </span>
                    <span className={styles.execCol}>{exec.callCount != null ? formatNumber(exec.callCount) : "—"}</span>
                    <span className={styles.execCol}>{exec.rowsExamined != null ? formatNumber(exec.rowsExamined) : "—"}</span>
                    <span className={styles.execCol}>
                      <span className={styles.execBarTrack}>
                        <span className={`${styles.execBarFill} ${isWorst ? styles.execBarFillWorst : ""}`} style={{ width: `${barPct}%` }} />
                      </span>
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        ) : (
          <div className={styles.execEmptyState}>
            <Clock size={20} className={styles.execEmptyIcon} />
            <p>No execution snapshots yet</p>
            <span>Run slow query analysis multiple times to build a performance history for this query</span>
          </div>
        )}
      </div>
    );
  };

  const renderRewriteTab = () => {
    // State: no analysis run yet
    if (!optimization && !isOptimizing) {
      return (
        <div className={styles.tabContent}>
          <div className={styles.rewriteGate}>
            <Sparkles size={28} className={styles.rewriteGateIcon} />
            <h4 className={styles.rewriteGateTitle}>Query Rewrite Analysis</h4>
            <p className={styles.rewriteGateDesc}>
              Click below to attempt an AI-powered rewrite. The rewrite will only be shown if it
              produces the same results AND improves performance by at least 15%.
            </p>
            <button className={styles.rewriteGateBtn} onClick={() => onOptimize?.(query, {})}>
              <Sparkles size={14} />
              Analyze &amp; Attempt Rewrite
            </button>
          </div>
        </div>
      );
    }

    // State: optimizing in progress
    if (isOptimizing) {
      return (
        <div className={styles.tabContent}>
          <div className={styles.rewriteLoading}>
            <div className={styles.spinner} />
            <span>{optimizationSteps.length === 0 ? "Starting rewrite analysis..." : optimizationSteps[optimizationSteps.length - 1]?.message}</span>
          </div>
          <OptimizationStepList steps={optimizationSteps} />
        </div>
      );
    }

    // State: analysis done but no accepted rewrite
    if (!rewrittenSql) {
      const rejectionStep = optimizationSteps.slice().reverse().find(
        (s) => ["rewrite_rejected", "rewrite_incorrect", "no_rewrite", "benchmark_skipped"].includes(s.status)
      );
      const reason = rejectionStep?.detail || rejectionStep?.message || null;

      return (
        <div className={styles.tabContent}>
          <div className={styles.rewriteRejected}>
            <div className={styles.rewriteRejectedHeader}>
              <AlertTriangle size={18} className={styles.rewriteRejectedIcon} />
              <h4 className={styles.rewriteRejectedTitle}>Query Rewrite Not Applicable</h4>
            </div>
            <p className={styles.rewriteRejectedDesc}>
              {rejectionStep?.status === "rewrite_incorrect"
                ? "A rewrite was generated but it produced different results — discarded to preserve correctness."
                : rejectionStep?.status === "rewrite_rejected"
                ? "A rewrite was generated and benchmarked, but it did not improve performance significantly."
                : "No beneficial rewrite could be produced for this query pattern."}
            </p>
            {reason && reason !== rejectionStep?.message && (
              <p className={styles.rewriteRejectedDetail}>{reason}</p>
            )}
            <div className={styles.rewriteRejectedHint}>
              <Info size={12} />
              <span>
                The performance bottleneck is likely due to the underlying data access pattern (e.g., full table scan,
                missing index, large dataset). See the <strong>Overview</strong> tab for index and schema recommendations.
              </span>
            </div>
          </div>
          {/* Show all steps for transparency */}
          {optimizationSteps.length > 0 && <OptimizationStepList steps={optimizationSteps} />}
        </div>
      );
    }

    // State: accepted rewrite — show comparison
    return (
      <div className={styles.tabContent}>
        {/* Runtime delta */}
        {(baselineRuntime != null || rewriteRuntime != null) && (
          <div className={styles.runtimeDeltaRow}>
            <span className={styles.runtimeOld}>
              {baselineRuntime != null ? formatDuration(baselineRuntime) : "—"}
              <span className={styles.runtimeOldLabel}>avg</span>
            </span>
            <span className={styles.runtimeArrow}>→</span>
            <span className={styles.runtimeNew}>
              {rewriteRuntime != null ? formatDuration(rewriteRuntime) : <span className={styles.runtimePending}>—</span>}
              {rewriteRuntime != null && <span className={styles.runtimeNewLabel}>{rewriteIsMeasured ? "bench" : "est."}</span>}
            </span>
            {compareDeltaPct != null && (
              <span className={`${styles.deltaTag} ${compareDeltaPct >= 0 ? styles.deltaTagGood : styles.deltaTagBad}`}>
                {compareDeltaPct >= 0 ? "-" : "+"}{Math.abs(compareDeltaPct).toFixed(1)}%
                {compareDeltaPct >= 0 ? " faster" : " slower"}
              </span>
            )}
            {compareDeltaPct == null && baselineRuntime != null && rewriteRuntime == null && onBenchmarkCandidates && (
              <button type="button" className={styles.benchmarkButton} onClick={() => onBenchmarkCandidates(query)} disabled={isBenchmarkingCandidates}>
                {isBenchmarkingCandidates ? "Benchmarking..." : "Run Benchmark"}
              </button>
            )}
          </div>
        )}

        {/* Row count validation */}
        {(originalRowCount != null || rewriteRowCount != null) && (
          <div className={`${styles.rowCountBar} ${rowCountMismatch ? styles.rowCountBarWarn : zeroRowBenchmark ? styles.rowCountBarZero : styles.rowCountBarOk}`}>
            {rowCountMismatch || zeroRowBenchmark ? <AlertTriangle size={11} /> : <Check size={11} />}
            <span>
              {zeroRowBenchmark && !rowCountMismatch
                ? "Original returned 0 rows — benchmark may not reflect production performance"
                : rowCountMismatch
                ? `Row count mismatch: original ${formatNumber(originalRowCount)}, rewrite ${formatNumber(rewriteRowCount)}`
                : `Rows match (${formatNumber(originalRowCount)}) — semantically consistent`}
            </span>
          </div>
        )}

        {/* Original vs Rewritten comparison */}
        <div className={styles.queryCompareBlock}>
          <div className={styles.queryCompareTabs}>
            <div className={styles.queryCompareTabsLeft}>
              {originalSql && (
                <button className={`${styles.queryCompareTab} ${activeCompareTab === "original" ? styles.queryCompareTabActive : ""}`} onClick={() => setActiveCompareTab("original")}>
                  Original
                  {baselineRuntime != null && <span className={styles.queryCompareRuntime}>{formatDuration(baselineRuntime)}</span>}
                </button>
              )}
              <button className={`${styles.queryCompareTab} ${activeCompareTab === "rewrite" ? styles.queryCompareTabActive : ""}`} onClick={() => setActiveCompareTab("rewrite")}>
                Rewritten
                {rewriteRuntime != null && <span className={styles.queryCompareRuntime}>{formatDuration(rewriteRuntime)}</span>}
              </button>
            </div>
            {activeCompareSql && (
              <button className={`${styles.copyActionBtn} ${copiedId === "compare" ? styles.copyActionBtnCopied : ""}`} onClick={() => handleCopy(activeCompareSql, "compare")}>
                {copiedId === "compare" ? <Check size={12} /> : <Copy size={12} />}
                {copiedId === "compare" ? "Copied" : "Copy"}
              </button>
            )}
          </div>
          <pre className={styles.queryCodeInner}><code>{activeCompareSql || "Query text not available."}</code></pre>
        </div>

        {optimizationSteps.length > 0 && <OptimizationStepList steps={optimizationSteps} />}
      </div>
    );
  };

  const renderExplainTab = () => (
    <div className={`${styles.tabContent} ${styles.explainTab}`}>
      {hasRealTreeData ? (
        <>
          {/* Summary stats */}
          {(() => {
            const rootNode = parsedTreeNodes[0];
            const execTimeMs = rootNode?.actualTimeEnd ?? explainAnalysis.executionTimeMs ?? explainAnalysis.totalTimeMs ?? null;
            const rootRows = rootNode?.actualRows ?? null;
            const totalCost = rootNode?.cost ?? planTree?.totalCost ?? explainAnalysis.estimatedCost ?? null;
            return (
              <div className={styles.planStats}>
                {execTimeMs != null && (
                  <div className={styles.planStat}>
                    <span className={styles.planStatLabel}>Execution Time</span>
                    <span className={styles.planStatValue}>{execTimeMs >= 1000 ? `${(execTimeMs / 1000).toFixed(2)}s` : `${Math.round(execTimeMs)}ms`}</span>
                  </div>
                )}
                {rootRows != null && (
                  <div className={styles.planStat}>
                    <span className={styles.planStatLabel}>Result Rows</span>
                    <span className={styles.planStatValue}>{formatNumber(rootRows)}</span>
                  </div>
                )}
                {totalCost != null && (
                  <div className={styles.planStat}>
                    <span className={styles.planStatLabel}>Est. Cost</span>
                    <span className={styles.planStatValue}>{formatCost(totalCost)}</span>
                  </div>
                )}
                <div className={styles.planStat}>
                  <span className={styles.planStatLabel}>Operations</span>
                  <span className={styles.planStatValue}>{parsedTreeNodes.length}</span>
                </div>
              </div>
            );
          })()}

          {/* Tree / List toggle */}
          <div className={styles.section}>
            <div className={styles.treeSectionHeader}>
              <h3 className={styles.sectionTitle}>Execution Plan</h3>
              <div className={styles.treeControls}>
                <div className={styles.viewToggle}>
                  <button type="button" className={`${styles.viewToggleBtn} ${explainViewMode === "tree" ? styles.viewToggleBtnActive : ""}`} onClick={() => setExplainViewMode("tree")}>Tree</button>
                  <button type="button" className={`${styles.viewToggleBtn} ${explainViewMode === "list" ? styles.viewToggleBtnActive : ""}`} onClick={() => setExplainViewMode("list")}>List</button>
                </div>
                {explainViewMode === "list" && (
                  <>
                    <button type="button" className={styles.treeControlBtn} onClick={expandAllTreeNodes}>Expand All</button>
                    <button type="button" className={styles.treeControlBtn} onClick={collapseAllTreeNodes}>Collapse All</button>
                  </>
                )}
              </div>
            </div>

            {explainViewMode === "tree" && (
              <div className={styles.vtreeScroll}>
                <div className={styles.vtreeCanvas}>
                  {treeHierarchy.map((rootNode) => {
                    const renderVisualNode = (n) => {
                      const isSlow = n.actualTimeEnd != null && maxTreeTime > 0 && n.actualTimeEnd > maxTreeTime * 0.5;
                      const isSelected = selectedVisualNodeId === n.id;
                      const timeFmt = n.actualTimeEnd != null ? (n.actualTimeEnd >= 1000 ? `${(n.actualTimeEnd / 1000).toFixed(2)}s` : `${Math.round(n.actualTimeEnd)}ms`) : null;
                      const timeBarWidth = maxTreeTime > 0 && n.actualTimeEnd != null ? Math.max(2, (n.actualTimeEnd / maxTreeTime) * 100) : 0;
                      const opName = n.operation.length > 32 ? `${n.operation.substring(0, 30)}...` : n.operation;
                      const rowAccuracy = n.estRows != null && n.actualRows != null && n.estRows > 0 ? n.actualRows / n.estRows : null;
                      return (
                        <div key={n.id} className={styles.vtreeGroup}>
                          <div className={`${styles.vtreeCard} ${isSlow ? styles.vtreeCardSlow : ""} ${isSelected ? styles.vtreeCardSelected : ""}`}
                            onClick={(e) => { e.stopPropagation(); setSelectedVisualNodeId(isSelected ? null : n.id); }}>
                            <span className={styles.vtreeCardOp} title={n.operation}>{opName}</span>
                            {timeFmt && <span className={`${styles.vtreeCardTime} ${isSlow ? styles.vtreeCardTimeSlow : ""}`}>{timeFmt}</span>}
                            {timeBarWidth > 0 && <span className={styles.vtreeCardBar}><span className={`${styles.vtreeCardBarFill} ${isSlow ? styles.vtreeCardBarSlow : ""}`} style={{ width: `${timeBarWidth}%` }} /></span>}
                          </div>
                          {isSelected && (
                            <div className={styles.vtreeDetail}>
                              <div className={styles.vtreeDetailTitle}>{n.operation}</div>
                              <div className={styles.vtreeDetailGrid}>
                                {n.actualTimeStart != null && n.actualTimeEnd != null && (<div className={styles.vtreeDetailItem}><span className={styles.vtreeDetailLabel}>Time</span><span className={styles.vtreeDetailValue}>{n.actualTimeStart.toFixed(1)}..{n.actualTimeEnd.toFixed(1)}ms</span></div>)}
                                {n.actualRows != null && (<div className={styles.vtreeDetailItem}><span className={styles.vtreeDetailLabel}>Rows</span><span className={styles.vtreeDetailValue}>{formatNumber(n.actualRows)}</span></div>)}
                                {n.estRows != null && (<div className={styles.vtreeDetailItem}><span className={styles.vtreeDetailLabel}>Est.</span><span className={styles.vtreeDetailValue}>{formatNumber(n.estRows)}</span></div>)}
                                {rowAccuracy != null && (<div className={styles.vtreeDetailItem}><span className={styles.vtreeDetailLabel}>Accuracy</span><span className={`${styles.vtreeDetailValue} ${rowAccuracy > 10 || rowAccuracy < 0.1 ? styles.treeDetailValueWarn : ""}`}>{rowAccuracy >= 100 ? `${Math.round(rowAccuracy)}x` : `${rowAccuracy.toFixed(1)}x`}</span></div>)}
                                {n.cost != null && (<div className={styles.vtreeDetailItem}><span className={styles.vtreeDetailLabel}>Cost</span><span className={styles.vtreeDetailValue}>{formatCost(n.cost)}</span></div>)}
                                {n.loops != null && (<div className={styles.vtreeDetailItem}><span className={styles.vtreeDetailLabel}>Loops</span><span className={`${styles.vtreeDetailValue} ${n.loops > 100 ? styles.treeDetailValueWarn : ""}`}>{formatNumber(n.loops)}</span></div>)}
                              </div>
                              {timeBarWidth > 0 && (<div className={styles.vtreeDetailBarRow}><span className={styles.vtreeDetailBarTrack}><span className={`${styles.vtreeDetailBarFill} ${isSlow ? styles.vtreeDetailBarSlow : ""}`} style={{ width: `${timeBarWidth}%` }} /></span><span className={styles.vtreeDetailBarPct}>{Math.round(timeBarWidth)}%</span></div>)}
                            </div>
                          )}
                          {n.children.length > 0 && (
                            <>
                              <div className={styles.vtreeLineDown} />
                              <div className={styles.vtreeChildren}>
                                {n.children.map((child, ci) => (
                                  <div key={child.id} className={`${styles.vtreeChildWrap} ${n.children.length === 1 ? styles.vtreeChildOnly : ""} ${ci === 0 ? styles.vtreeChildFirst : ""} ${ci === n.children.length - 1 ? styles.vtreeChildLast : ""}`}>
                                    {renderVisualNode(child)}
                                  </div>
                                ))}
                              </div>
                            </>
                          )}
                        </div>
                      );
                    };
                    return renderVisualNode(rootNode);
                  })}
                </div>
              </div>
            )}

            {explainViewMode === "list" && (
              <div className={styles.interactiveTree}>
                {treeHierarchy.map((node) => {
                  const renderNode = (n, depth) => {
                    const isSlow = n.actualTimeEnd != null && maxTreeTime > 0 && n.actualTimeEnd > maxTreeTime * 0.5;
                    const isExpanded = expandedTreeNodeIds.has(n.id);
                    const timeBarWidth = maxTreeTime > 0 && n.actualTimeEnd != null ? Math.max(2, (n.actualTimeEnd / maxTreeTime) * 100) : 0;
                    const timeFmt = n.actualTimeEnd != null ? (n.actualTimeEnd >= 1000 ? `${(n.actualTimeEnd / 1000).toFixed(2)}s` : `${Math.round(n.actualTimeEnd)}ms`) : null;
                    const rowAccuracy = n.estRows != null && n.actualRows != null && n.estRows > 0 ? n.actualRows / n.estRows : null;
                    return (
                      <div key={n.id} className={styles.treeNodeWrap}>
                        <div className={`${styles.treeNodeRow} ${isSlow ? styles.treeNodeRowSlow : ""} ${isExpanded ? styles.treeNodeRowExpanded : ""}`}
                          style={{ paddingLeft: `${depth * 24 + 8}px` }} onClick={() => toggleTreeNode(n.id)}>
                          <span className={styles.treeToggle}>
                            {n.children.length > 0 ? (isExpanded ? <ChevronDown size={12} /> : <ChevronRight size={12} />) : <Circle size={5} className={styles.treeLeafDot} />}
                          </span>
                          <span className={styles.treeNodeOp}>{n.operation}</span>
                          {timeFmt && <span className={`${styles.treeTimeBadge} ${isSlow ? styles.treeTimeBadgeSlow : ""}`}>{timeFmt}</span>}
                          {timeBarWidth > 0 && <span className={styles.treeInlineBar}><span className={`${styles.treeInlineBarFill} ${isSlow ? styles.treeInlineBarSlow : ""}`} style={{ width: `${timeBarWidth}%` }} /></span>}
                        </div>
                        {isExpanded && (
                          <div className={styles.treeDetailPanel} style={{ marginLeft: `${depth * 24 + 28}px` }}>
                            <div className={styles.treeDetailGrid}>
                              {n.actualTimeStart != null && n.actualTimeEnd != null && (<div className={styles.treeDetailItem}><span className={styles.treeDetailLabel}>Actual Time</span><span className={`${styles.treeDetailValue} ${isSlow ? styles.treeDetailValueSlow : ""}`}>{n.actualTimeStart.toFixed(3)}..{n.actualTimeEnd.toFixed(3)} ms</span></div>)}
                              {n.actualRows != null && (<div className={styles.treeDetailItem}><span className={styles.treeDetailLabel}>Rows</span><span className={styles.treeDetailValue}>{formatNumber(n.actualRows)}</span></div>)}
                              {n.estRows != null && (<div className={styles.treeDetailItem}><span className={styles.treeDetailLabel}>Est. Rows</span><span className={styles.treeDetailValue}>{formatNumber(n.estRows)}</span></div>)}
                              {rowAccuracy != null && (<div className={styles.treeDetailItem}><span className={styles.treeDetailLabel}>Row Est. Accuracy</span><span className={`${styles.treeDetailValue} ${rowAccuracy > 10 || rowAccuracy < 0.1 ? styles.treeDetailValueWarn : ""}`}>{rowAccuracy >= 100 ? `${Math.round(rowAccuracy)}x` : `${rowAccuracy.toFixed(1)}x`}{rowAccuracy > 10 && " (off by >10x)"}</span></div>)}
                              {n.cost != null && (<div className={styles.treeDetailItem}><span className={styles.treeDetailLabel}>Cost</span><span className={styles.treeDetailValue}>{formatCost(n.cost)}</span></div>)}
                              {n.loops != null && (<div className={styles.treeDetailItem}><span className={styles.treeDetailLabel}>Loops</span><span className={`${styles.treeDetailValue} ${n.loops > 100 ? styles.treeDetailValueWarn : ""}`}>{formatNumber(n.loops)}{n.loops > 100 && " (high)"}</span></div>)}
                            </div>
                            {timeBarWidth > 0 && (<div className={styles.treeDetailBar}><div className={`${styles.treeDetailBarFill} ${isSlow ? styles.treeDetailBarSlow : ""}`} style={{ width: `${timeBarWidth}%` }} /><span className={styles.treeDetailBarLabel}>{Math.round(timeBarWidth)}% of total time</span></div>)}
                          </div>
                        )}
                        {n.children.map((child) => renderNode(child, depth + 1))}
                      </div>
                    );
                  };
                  return renderNode(node, 0);
                })}
              </div>
            )}
          </div>

          {/* Performance Issues */}
          {issues.length > 0 && (
            <div className={styles.section}>
              <div className={styles.collapsibleHeader} onClick={() => toggleSection("issues")}>
                {expandedSections.issues ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                <h3 className={styles.sectionTitle}>Performance Issues</h3>
                <span className={styles.sectionCount}>{issues.length}</span>
              </div>
              {expandedSections.issues && (
                <div className={styles.issuesList}>
                  {issues.map((issue, idx) => (
                    <div key={idx} className={styles.issueCard}>
                      <span className={`${styles.issueSeverity} ${styles[`severity${(issue.severity || "medium").toLowerCase()}`] || ""}`}>{(issue.severity || "MEDIUM").toUpperCase()}</span>
                      <span className={styles.issueDesc}>{issue.description || issue.message || JSON.stringify(issue)}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* AI Summary */}
          {explainAnalysis.aiSummary && !explainAnalysis.planParseError && (() => {
            const raw = explainAnalysis.aiSummary;
            const sections = [];
            let current = { title: "", lines: [] };
            for (const line of raw.split("\n")) {
              const trimmed = line.trim();
              if (/^---+$/.test(trimmed)) continue;
              const headingMatch = trimmed.match(/^#{1,3}\s+(?:\d+\.\s*)?(.+)/);
              if (headingMatch) { if (current.title || current.lines.length) sections.push(current); current = { title: headingMatch[1].trim(), lines: [] }; }
              else if (trimmed) current.lines.push(trimmed);
            }
            if (current.title || current.lines.length) sections.push(current);
            return (
              <div className={styles.section}>
                <h3 className={styles.sectionTitle}>AI Summary</h3>
                <div className={styles.aiSummaryFormatted}>
                  {sections.map((sec, si) => (
                    <div key={si} className={styles.aiSummarySection}>
                      {sec.title && <h4 className={styles.aiSummarySectionTitle}>{sec.title}</h4>}
                      {sec.lines.map((line, li) => {
                        if (/^```/.test(line)) return null;
                        if (/^[A-Z_]+\(/.test(line) || /^\w+\.\w+\s/.test(line) || line.startsWith("u.") || line.startsWith("`")) {
                          return <code key={li} className={styles.aiSummaryCode}>{line.replace(/^`+|`+$/g, "")}</code>;
                        }
                        if (/^[-*]\s/.test(line)) {
                          const text = line.replace(/^[-*]\s+/, "");
                          const boldMatch = text.match(/^\*\*(.+?)\*\*[:\s]*(.*)/);
                          return <div key={li} className={styles.aiSummaryBullet}><span className={styles.aiSummaryBulletDot} />{boldMatch ? <span><strong>{boldMatch[1]}</strong>{boldMatch[2] ? `: ${boldMatch[2]}` : ""}</span> : <span>{text.replace(/\*\*/g, "")}</span>}</div>;
                        }
                        return <p key={li} className={styles.aiSummaryPara}>{line.replace(/\*\*/g, "").replace(/`([^`]+)`/g, "$1")}</p>;
                      })}
                    </div>
                  ))}
                </div>
              </div>
            );
          })()}

          {/* Raw Plan Tree */}
          <div className={styles.section}>
            <div className={styles.collapsibleHeader} onClick={() => toggleSection("planTree")}>
              {expandedSections.planTree ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
              <h3 className={styles.sectionTitle}>Raw Query Plan</h3>
            </div>
            {expandedSections.planTree && (
              <pre className={styles.planTreeCode}>
                <code>{(() => {
                  const raw = explainAnalysis.planText || explainAnalysis.planJson;
                  if (!raw) return JSON.stringify(planTree, null, 2);
                  try { const parsed = JSON.parse(raw); if (Array.isArray(parsed) && parsed[0]?.raw) return parsed[0].raw; return raw; } catch { return raw; }
                })()}</code>
              </pre>
            )}
          </div>
        </>
      ) : planTree ? (
        <>
          {explainAnalysis.aiSummary && (<div className={styles.section}><h3 className={styles.sectionTitle}>AI Summary</h3><p className={styles.aiSummaryText}>{explainAnalysis.aiSummary}</p></div>)}
          <div className={styles.section}><pre className={styles.planTreeCode}><code>{JSON.stringify(planTree, null, 2)}</code></pre></div>
        </>
      ) : (
        <div className={styles.emptyState}>
          <BarChart2 size={24} className={styles.emptyIcon} />
          <p>No EXPLAIN plan available</p>
          <span>EXPLAIN analysis is available for SELECT queries after running analysis</span>
        </div>
      )}
    </div>
  );

  // ── Main render ───────────────────────────────────────────────────────────

  return (
    <div className={styles.dialogOverlay} onClick={handleClose}>
      <div className={styles.dialogContent} onClick={(e) => e.stopPropagation()}>

        {/* Header */}
        <div className={styles.header}>
          <div className={styles.headerLeft}>
            <h2 className={styles.title}>Query Analysis</h2>
            {query.severity && (
              <span className={`${styles.severityBadge} ${styles[query.severity?.toLowerCase()]}`}>{query.severity}</span>
            )}
          </div>
          <div className={styles.headerRight}>
            {optimization?.cached && (
              <span className={styles.cachedBadge} title={`Cached ${optimization.generatedAt ? new Date(optimization.generatedAt).toLocaleString() : ""}`}>
                <Clock size={12} />Cached
              </span>
            )}
            <button className={styles.closeBtn} onClick={handleClose}><X size={18} /></button>
          </div>
        </div>

        {/* Content */}
        <div className={styles.content}>
          {/* Metrics strip — always visible */}
          <div className={styles.metricsStrip}>
            <div className={styles.metricChip}><span className={styles.metricChipLabel}>Avg</span><span className={styles.metricChipValue}>{formatDuration(query.avgDurationMs || query.averageDurationMs)}</span></div>
            <div className={styles.metricChipDivider} />
            <div className={styles.metricChip}><span className={styles.metricChipLabel}>Max</span><span className={styles.metricChipValue}>{formatDuration(query.maxDurationMs || query.maxExecutionTimeMs)}</span></div>
            <div className={styles.metricChipDivider} />
            <div className={styles.metricChip}><span className={styles.metricChipLabel}>Calls</span><span className={styles.metricChipValue}>{formatNumber(query.callCount || query.executionCount)}</span></div>
            {query.rowsExamined != null && (<><div className={styles.metricChipDivider} /><div className={styles.metricChip}><span className={styles.metricChipLabel}>Rows Examined</span><span className={styles.metricChipValue}>{formatNumber(query.rowsExamined)}</span></div></>)}
            {query.totalExecutionTimeMs != null && (<><div className={styles.metricChipDivider} /><div className={styles.metricChip}><span className={styles.metricChipLabel}>Total Time</span><span className={styles.metricChipValue}>{formatDuration(query.totalExecutionTimeMs)}</span></div></>)}
            {query.impactScore != null && (<><div className={styles.metricChipDivider} /><div className={styles.metricChip}><span className={styles.metricChipLabel}>Impact</span><span className={styles.metricChipValue}>{query.impactScore.toFixed(1)}</span></div></>)}
          </div>

          {/* Query — always visible, scrollable */}
          <div className={styles.querySection}>
            <div className={styles.queryHeader}>
              <span className={styles.querySectionLabel}>{hasSampleLiterals ? "Query · with values" : "Query"}</span>
              <div className={styles.queryActions}>
                {hasSampleLiterals ? (
                  <>
                    <button className={`${styles.copyActionBtn} ${copiedId === "literals" ? styles.copyActionBtnCopied : ""}`} onClick={() => handleCopy(displayQuery, "literals")}>
                      {copiedId === "literals" ? <Check size={12} /> : <Copy size={12} />}{copiedId === "literals" ? "Copied" : "Copy"}
                    </button>
                    <button className={`${styles.copyActionBtn} ${styles.copyActionBtnSecondary} ${copiedId === "normalized" ? styles.copyActionBtnCopied : ""}`} onClick={() => handleCopy(normalizedQuery, "normalized")} title="Copy without literal values">
                      {copiedId === "normalized" ? <Check size={12} /> : <Copy size={12} />}{copiedId === "normalized" ? "Copied" : "Copy normalized"}
                    </button>
                  </>
                ) : (
                  <button className={`${styles.copyActionBtn} ${copiedId === "query" ? styles.copyActionBtnCopied : ""}`} onClick={() => handleCopy(displayQuery, "query")}>
                    {copiedId === "query" ? <Check size={12} /> : <Copy size={12} />}{copiedId === "query" ? "Copied" : "Copy"}
                  </button>
                )}
              </div>
            </div>
            <pre className={styles.queryCodeInner}><code>{displayQuery}</code></pre>
          </div>

          {/* ── Pre/During optimization: CTA or loading ── */}
          {!showTabView && (
            <div className={styles.aiRewriteSection}>
              <div className={styles.aiRewriteHeader}>
                <div className={styles.aiRewriteTitle}>
                  <Sparkles size={14} className={styles.sparkleIcon} />
                  AI Rewrite
                </div>
                <button className={styles.rewriteBtn} onClick={() => onOptimize?.(query, { forceRefresh: !!optimization?.cached })} disabled={isOptimizing}>
                  {isOptimizing ? (<><div className={styles.spinnerSmall} />Analyzing...</>) : (<><Sparkles size={13} />Analyze &amp; Optimize</>)}
                </button>
              </div>
              {isOptimizing ? (
                <div className={styles.rewriteLoading}>
                  <div className={styles.spinner} />
                  <span>{optimizationSteps.length === 0 ? "Starting analysis..." : optimizationSteps[optimizationSteps.length - 1]?.message}</span>
                  <OptimizationStepList steps={optimizationSteps} />
                </div>
              ) : (
                <div className={styles.rewriteEmptyHint}>
                  One click to get a rewritten query, index recommendations, and root cause analysis.
                </div>
              )}
            </div>
          )}

          {/* ── Post-optimization: 4 tabs ── */}
          {showTabView && (
            <div className={styles.analysisArea}>
              {/* Tab bar */}
              <div className={styles.analysisTabBar}>
                <div className={styles.analysisTabList}>
                  {tabs.map((tab) => (
                    <button
                      key={tab.id}
                      className={`${styles.analysisTab} ${activeTab === tab.id ? styles.analysisTabActive : ""} ${tab.disabled ? styles.analysisTabDisabled : ""}`}
                      onClick={() => !tab.disabled && setActiveTab(tab.id)}
                      disabled={tab.disabled}
                    >
                      <tab.icon size={13} className={styles.analysisTabIcon} />
                      {tab.label}
                      {tab.id === "rewrite" && optimization && !isOptimizing && (
                        <span className={`${styles.analysisTabBadge} ${rewrittenSql ? styles.analysisTabBadgeGood : styles.analysisTabBadgeNone}`}>
                          {rewrittenSql ? "✓" : "—"}
                        </span>
                      )}
                    </button>
                  ))}
                </div>
                {/* Re-analyze button */}
                <button
                  className={styles.reanalyzeBtn}
                  onClick={() => onOptimize?.(query, { forceRefresh: true })}
                  disabled={isOptimizing}
                  title="Re-run analysis"
                >
                  <RefreshCw size={12} />
                  Re-analyze
                </button>
              </div>

              {/* Tab content */}
              {activeTab === "overview" && renderOverviewTab()}
              {activeTab === "executions" && renderExecutionsTab()}
              {activeTab === "rewrite" && renderRewriteTab()}
              {activeTab === "explain" && renderExplainTab()}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
