-- Playbook System Tables

-- Table: playbooks
-- Stores playbook definitions
CREATE TABLE playbooks (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    db_type VARCHAR(20), -- 'mysql', 'postgres', 'all'
    category VARCHAR(50), -- 'health', 'performance', 'maintenance', 'troubleshooting'
    schedule_cron VARCHAR(100), -- Cron expression for automatic execution
    is_active BOOLEAN DEFAULT TRUE,
    is_system BOOLEAN DEFAULT FALSE, -- System playbooks can't be deleted
    steps JSON NOT NULL, -- Array of step definitions
    alert_config JSON, -- Alert configuration (channels, thresholds)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_category (category),
    INDEX idx_db_type (db_type),
    INDEX idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: playbook_runs
-- Tracks execution history
CREATE TABLE playbook_runs (
    id VARCHAR(36) PRIMARY KEY,
    playbook_id VARCHAR(36) NOT NULL,
    connection_id VARCHAR(36) NOT NULL,
    status VARCHAR(20) NOT NULL, -- 'running', 'completed', 'failed', 'cancelled'
    trigger_type VARCHAR(20), -- 'manual', 'scheduled', 'alert'
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP NULL,
    duration_ms BIGINT,
    steps_total INT DEFAULT 0,
    steps_completed INT DEFAULT 0,
    findings JSON, -- Array of findings from each step
    recommendations JSON, -- Generated recommendations
    alerts_triggered INT DEFAULT 0,
    error_message TEXT,
    FOREIGN KEY (playbook_id) REFERENCES playbooks(id) ON DELETE CASCADE,
    INDEX idx_playbook (playbook_id),
    INDEX idx_connection (connection_id),
    INDEX idx_status (status),
    INDEX idx_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: playbook_tools
-- Registry of safe database inspection tools
CREATE TABLE playbook_tools (
    id VARCHAR(36) PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    db_type VARCHAR(20), -- 'mysql', 'postgres', 'all'
    category VARCHAR(50), -- 'monitoring', 'analysis', 'inspection'
    is_readonly BOOLEAN DEFAULT TRUE,
    requires_params BOOLEAN DEFAULT FALSE,
    param_schema JSON, -- JSON schema for parameters
    sql_template TEXT, -- SQL template with placeholders
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_name (name),
    INDEX idx_db_type (db_type),
    INDEX idx_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: playbook_schedules
-- Manages scheduled playbook executions
CREATE TABLE playbook_schedules (
    id VARCHAR(36) PRIMARY KEY,
    playbook_id VARCHAR(36) NOT NULL,
    connection_id VARCHAR(36) NOT NULL,
    cron_expression VARCHAR(100) NOT NULL,
    is_enabled BOOLEAN DEFAULT TRUE,
    last_run_at TIMESTAMP NULL,
    next_run_at TIMESTAMP NULL,
    total_runs INT DEFAULT 0,
    successful_runs INT DEFAULT 0,
    failed_runs INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (playbook_id) REFERENCES playbooks(id) ON DELETE CASCADE,
    INDEX idx_playbook (playbook_id),
    INDEX idx_connection (connection_id),
    INDEX idx_next_run (next_run_at),
    INDEX idx_enabled (is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Table: playbook_alerts
-- Stores alerts generated by playbook runs
CREATE TABLE playbook_alerts (
    id VARCHAR(36) PRIMARY KEY,
    playbook_run_id VARCHAR(36) NOT NULL,
    connection_id VARCHAR(36) NOT NULL,
    severity VARCHAR(20) NOT NULL, -- 'info', 'warning', 'critical'
    title VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    findings JSON,
    recommendations JSON,
    acknowledged BOOLEAN DEFAULT FALSE,
    acknowledged_by VARCHAR(255),
    acknowledged_at TIMESTAMP NULL,
    channels_sent JSON, -- ["slack", "email", "browser"]
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (playbook_run_id) REFERENCES playbook_runs(id) ON DELETE CASCADE,
    INDEX idx_run (playbook_run_id),
    INDEX idx_connection (connection_id),
    INDEX idx_severity (severity),
    INDEX idx_acknowledged (acknowledged),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Insert system playbooks
INSERT INTO playbooks (id, name, description, db_type, category, schedule_cron, is_active, is_system, steps, alert_config) VALUES
(
    'pb-daily-health',
    'Daily Health Check',
    'Comprehensive daily database health assessment covering connections, slow queries, index usage, and table bloat',
    'all',
    'health',
    '0 9 * * *',
    TRUE,
    TRUE,
    JSON_ARRAY(
        JSON_OBJECT('tool', 'check_connection_count', 'name', 'Check Active Connections', 'thresholds', JSON_OBJECT('warning', 80, 'critical', 95)),
        JSON_OBJECT('tool', 'analyze_slow_queries', 'name', 'Analyze Slow Queries', 'params', JSON_OBJECT('limit', 10, 'min_duration_ms', 1000)),
        JSON_OBJECT('tool', 'check_index_usage', 'name', 'Check Index Usage', 'params', JSON_OBJECT('min_scans', 100)),
        JSON_OBJECT('tool', 'check_table_bloat', 'name', 'Check Table Bloat', 'thresholds', JSON_OBJECT('bloat_ratio', 0.3)),
        JSON_OBJECT('tool', 'generate_summary', 'name', 'Generate Health Summary')
    ),
    JSON_OBJECT('channels', JSON_ARRAY('browser'), 'severity_threshold', 'warning')
),
(
    'pb-high-cpu',
    'High CPU Investigation',
    'Troubleshooting workflow for high CPU usage - identifies expensive queries, missing indexes, and connection issues',
    'all',
    'troubleshooting',
    NULL,
    TRUE,
    TRUE,
    JSON_ARRAY(
        JSON_OBJECT('tool', 'get_active_queries', 'name', 'Get Active Queries'),
        JSON_OBJECT('tool', 'get_long_running_queries', 'name', 'Find Long Running Queries', 'params', JSON_OBJECT('min_duration_ms', 5000)),
        JSON_OBJECT('tool', 'analyze_query_plans', 'name', 'Analyze Query Plans'),
        JSON_OBJECT('tool', 'check_missing_indexes', 'name', 'Check for Missing Indexes'),
        JSON_OBJECT('tool', 'check_connection_count', 'name', 'Check Connection Count'),
        JSON_OBJECT('tool', 'generate_recommendations', 'name', 'Generate Recommendations')
    ),
    JSON_OBJECT('channels', JSON_ARRAY('browser', 'slack'), 'severity_threshold', 'critical')
),
(
    'pb-slow-query',
    'Slow Query Analysis',
    'In-depth analysis of slow queries with execution plans and optimization recommendations',
    'all',
    'performance',
    NULL,
    TRUE,
    TRUE,
    JSON_ARRAY(
        JSON_OBJECT('tool', 'get_slow_queries', 'name', 'Get Slow Queries', 'params', JSON_OBJECT('limit', 20, 'min_duration_ms', 1000)),
        JSON_OBJECT('tool', 'analyze_query_patterns', 'name', 'Analyze Query Patterns'),
        JSON_OBJECT('tool', 'explain_queries', 'name', 'Explain Query Plans'),
        JSON_OBJECT('tool', 'suggest_indexes', 'name', 'Suggest Index Optimizations'),
        JSON_OBJECT('tool', 'generate_optimization_plan', 'name', 'Generate Optimization Plan')
    ),
    JSON_OBJECT('channels', JSON_ARRAY('browser'), 'severity_threshold', 'warning')
),
(
    'pb-connection-pool',
    'Connection Pool Monitoring',
    'Monitors connection pool health, identifies connection leaks, and recommends pool sizing',
    'all',
    'monitoring',
    '*/30 * * * *',
    TRUE,
    TRUE,
    JSON_ARRAY(
        JSON_OBJECT('tool', 'get_connection_stats', 'name', 'Get Connection Statistics'),
        JSON_OBJECT('tool', 'detect_connection_leaks', 'name', 'Detect Connection Leaks'),
        JSON_OBJECT('tool', 'analyze_connection_patterns', 'name', 'Analyze Connection Patterns'),
        JSON_OBJECT('tool', 'recommend_pool_size', 'name', 'Recommend Pool Sizing')
    ),
    JSON_OBJECT('channels', JSON_ARRAY('browser'), 'severity_threshold', 'warning')
),
(
    'pb-index-optimization',
    'Index Optimization Workflow',
    'Comprehensive index analysis: identifies missing, unused, and duplicate indexes',
    'all',
    'performance',
    '0 2 * * 0',
    TRUE,
    TRUE,
    JSON_ARRAY(
        JSON_OBJECT('tool', 'scan_all_indexes', 'name', 'Scan All Indexes'),
        JSON_OBJECT('tool', 'find_unused_indexes', 'name', 'Find Unused Indexes', 'params', JSON_OBJECT('min_days', 30)),
        JSON_OBJECT('tool', 'find_duplicate_indexes', 'name', 'Find Duplicate Indexes'),
        JSON_OBJECT('tool', 'find_missing_indexes', 'name', 'Find Missing Indexes'),
        JSON_OBJECT('tool', 'calculate_index_impact', 'name', 'Calculate Index Impact'),
        JSON_OBJECT('tool', 'generate_index_plan', 'name', 'Generate Index Maintenance Plan')
    ),
    JSON_OBJECT('channels', JSON_ARRAY('browser', 'email'), 'severity_threshold', 'info')
);
